print('반갑습니다. 계좌 이체를 위한 정보를 입력하세요.')
number1=input('출금 계좌 번호: ')
number2=input('입금 은행: ')
number3=input('입금 계좌 번호: ')
number4=input('수취인: ')
number5=input('이체 금액: ')
print('\n')
print('입력하신 정보는 아래와 같습니다.')
print('===================================')
print('-출금 계좌 번호: ', number1)
print('-입금 은행: ', number2)
print('-입금 계좌 번호: ', number3)
print('-수취인: ', number4)
print('-이체 금액: ', number5)
print('===================================')
